### ISSUE TITLE
[ISSUE] 2fa 로그인 한 후 새로고침 하면, 다시 2fa 인증 화면으로 돌아간다.

### ISSUE THREAD

**Issue by hleesa** [bukdu7seong/FE#109]
2fa 인증 화면의 5분 카운트 다운이 시작된다.
인증 코드는 메일로 날아오지 않는다.

리센드 버튼을 클릭하면 404 에러가 발생한다.

**Comment by sideseal** [comment]
2fa에서 새로고침하면 login으로 이동하는 것으로 변경
