### ISSUE TITLE
[ISSUE] 유저 네임 변경 (색연필) 클릭시 문제 발생

### ISSUE THREAD

**Issue by hleesa** [bukdu7seong/FE#124]
<img width="518" alt="image" src="https://github.com/bukdu7seong/FE/assets/108059445/bf2b5a4a-b7f1-4d98-a7d4-657717be4c92">

**Comment by sideseal** [comment]
크롬에 이런 탭이 있었군요... 크롬으로 확인해봐야겠어요...
