### ISSUE TITLE
[TODO] Profile 페이지 구현

### ISSUE THREAD

**Issue by junyjeon** [bukdu7seong/FE#13]
## 구현 사항

* 기능 구현
* bootstrap 적용

**Comment by sideseal** [comment]
처음 로그인하고 들어올 때 initUser 안 됨

navbar로 움직일 때 유저 정보 렌더링 안됨

**Comment by sideseal** [comment]
/login 후 /login이 프로필을 띄우긴 하지만 http 윈도우 바가 경로를 변경해서 출력하지는 않음
