### ISSUE TITLE
[TODO] 상태관리 구현

### ISSUE THREAD

**Issue by junyjeon** [bukdu7seong/FE#17]
<img width="348" alt="image" src="https://github.com/bukdu7seong/FE/assets/98337069/f3b77cbc-3f14-499a-83f9-037cb2bdbbe4">

**Comment by junyjeon** [comment]
현재 방식 - > PubSub 방식으로 변경 중. 확장성을 위해..?

현재 방식
![image](https://github.com/bukdu7seong/FE/assets/98337069/cddbb85a-4541-417e-bb9c-0925c5295911)

PubSub 방식
![image](https://github.com/bukdu7seong/FE/assets/98337069/11bd1612-37ae-43a2-9182-d4a3c116048d)

**Comment by sideseal** [comment]
만들어주신 store로 기본적인 상태 관리가 잘 구현되는 것 같습니다!! 감사합니다 ㅎㅎ
