### ISSUE TITLE
[ISSUE] 사이드바가 줄어들 때 스크롤 바가 생김

### ISSUE THREAD

**Issue by sideseal** [bukdu7seong/FE#34]
사이드바가 줄어들 때 스크롤바가 생기는 것 같은데, 스크롤 바 없이 쭉 줄어들게 하려면 어떻게 고쳐야 할까요....??

**Comment by sideseal** [comment]
사이드바를 반응형으로 변경해야 할 듯 하다.

**Comment by hleesa** [comment]
상단 네비게이션바로 변경
