### ISSUE TITLE
[ISSUE] Login 이슈들

### ISSUE THREAD

**Issue by sideseal** [bukdu7seong/FE#68]
42Auth로 로그인 완료 후, 토큰을 지운 다음 다시 Login page로 이동하고 나서 아이디/비밀번호 입력으로 로그인을 하면 Login failed alert 발생 
-> 2fa가 기본으로 활성화되어 있어서 서버에서 301 응답이 날아오기 때문. 2fa 활성화 시 아이디/비밀번호 로그인인 경우 2fa 인증 페이지로 이동해서 인증되어야 함

**Comment by sideseal** [comment]
check2FAEnabled 함수가 완성이 안된 것 같음
```
    const is2FAEnabled = await check2FAEnabled(accessToken);
    if (is2FAEnabled) {
      // isLoggedIn?
      route(routes, '/2fa', true, false); // 2FA 페이지로 리다이렉트
    } else {
      globalState.setState({ isLoggedIn: true });
    }
```

```
export function check2FAEnabled(accessToken) {
  return fetch(`${API_URL}/user/2fa`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });
}
```

그런데 checkLogin에서 2fa 체크가 왜 필요한건가요...?!?

**Comment by sideseal** [comment]
Cookie warning
<img width="828" alt="Screenshot 2024-03-25 at 4 52 22 PM" src="https://github.com/bukdu7seong/FE/assets/63810422/ddea0a52-b0ae-4a40-bf9a-c0aae0feb8ea">

**Comment by junyjeon** [comment]
2fa버튼에서 체크/해제 기능 때문에 만들어뒀던 것 같은데, 지금은 필요 없을 것 같습니다!

**Comment by sideseal** [comment]
넵 지워놓겠습니다!!

**Comment by sideseal** [comment]
[ISSUE] 회원가입 시 사진 전송할 때, 사진이 백엔드에 등록이 안되는 것 같아요...

**Comment by junyjeon** [comment]
formData가 어떻게 처리되고 있는지, ekwak님하고 상의 해볼게요!

**Comment by sideseal** [comment]
어느정도 해결된 것 같아서 이슈 닫겠습니다!
