### ISSUE TITLE
[ISSUE] 메인 프로필 페이지에서 새로고침 눌렀을 때, sign up 2fa 인증 화면으로 이동

### ISSUE THREAD

**Issue by hleesa** [bukdu7seong/FE#95]

**Comment by hleesa** [comment]
올바른 인증 코드 입력해도 에러가 발생함.
아이디 비밀번호 입력하는 페이지도 리다이렉트

<img width="613" alt="스크린샷 2024-03-30 오후 3 52 53" src="https://github.com/bukdu7seong/FE/assets/108059445/7ee74a4b-a702-4c94-8058-9a6ba147eb6a">

**Comment by hleesa** [comment]
인증 코드가 메일로 보내지지 않은 경우도 존재함.
리센드 코드를 누르면 아래와 같은 에러가 발생함.
<img width="618" alt="스크린샷 2024-03-30 오후 4 36 40" src="https://github.com/bukdu7seong/FE/assets/108059445/595727ab-167d-4e53-ba0d-edc508e781be">

**Comment by hleesa** [comment]
뒤로가기를 누르면 메인 프로필 화면으로 돌아갈 수도 있다.

**Comment by sideseal** [comment]
해결완료된 것 가틈
